name: weekly-fda-device-recall-refresh

on:
  schedule:
    # every Friday at 09:00 UTC  (03:00 America/Chicago)
    - cron: "0 9 * * FRI"
  workflow_dispatch:               # allows manual “Run workflow”

jobs:
  ingest:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      SUPABASE_CONN: ${{ secrets.SUPABASE_CONN }}   # still useful locally

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas python-dotenv

      - name: Run loader
        run: python load_sample.py
